version: '3'

services:
  hazarder-apache:
    image: hazarder_production:latest
    container_name: hazarder
    networks:
      - nginxdb_proxy
    volumes:
      - .:/var/www/html
      - ${SSL_CERT_DIR}:/etc/ssl/private
    command: /var/www/html/init.sh
    restart: always
    ports:
      - 443:443

networks:
  nginxdb_proxy:
    external: true
