version: '3'

services:
  hazarder-apache:
    image: hazarder_master:latest
    container_name: hazarder
    networks:
      - nginxdb_proxy
    volumes:
      - .:/var/www/html
    command: /var/www/html/init.sh
    restart: always
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=hazarder.local

networks:
  nginxdb_proxy:
    external: true