version: '3'

services:
  hazarder-apache:
    image: hazarder_production:latest
    container_name: hazarder
    networks:
      - nginxdb_proxy
    volumes:
      - .:/var/www/html
      - /etc/letsencrypt/live/vladino.me:/etc/ssl/private
    command: /var/www/html/init.sh
    restart: always
    expose:
      - 443
    environment:
      - VIRTUAL_HOST=vladino.me

networks:
  nginxdb_proxy:
    external: true
