version: '3'

services:
  hazarder-apache:
    image: vladino.me:5000/hazarder:local
    container_name: hazarder_local
    networks:
      - nginxdb_proxy
    volumes:
      - .:/var/www/html
    command: /var/www/html/init-local.sh
    restart: always
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=hazarder.local
      - TZ=Europe/Vienna

networks:
  nginxdb_proxy:
    external: true